git rm css/bootstrap-theme.css
git rm css/bootstrap-theme.min.css
git rm css/bootstrap.css
git rm css/bootstrap.min.css
git rm css/fontAwesome.css
git rm css/templatemo-style.css
git rm fonts/FontAwesome.otf
git rm fonts/fontawesome-webfont.eot
git rm fonts/fontawesome-webfont.svg
git rm fonts/fontawesome-webfont.ttf
git rm fonts/fontawesome-webfont.woff
git rm fonts/fontawesome-webfont.woff2
git rm fonts/glyphicons-halflings-regular.eot
git rm fonts/glyphicons-halflings-regular.svg
git rm fonts/glyphicons-halflings-regular.ttf
git rm fonts/glyphicons-halflings-regular.woff
git rm img/close.png
git rm img/contact-icon.png
git rm img/featured-icon.png
git rm img/home-icon.png
git rm img/item-01.jpg
git rm img/item-02.jpg
git rm img/item-03.jpg
git rm img/item-04.jpg
git rm img/item-05.jpg
git rm img/item-06.jpg
git rm img/item-07.jpg
git rm img/item-08.jpg
git rm img/left-about-image.jpg
git rm img/left-feature-image.png
git rm img/loading.gif
git rm img/logo.png
git rm img/next.png
git rm img/picCERN.png
git rm img/prev.png
git rm img/project-item-01.jpg
git rm img/project-item-02.jpg
git rm img/project-item-03.jpg
git rm img/project-item-04.jpg
git rm img/project-item-05.jpg
git rm img/project-item-06.jpg
git rm img/project-item-07.jpg
git rm img/project-item-08.jpg
git rm img/projects-icon.png
git rm img/prove-bg.png
git rm img/right-about-image.jpg
git rm img/skills.jpg
git rm index.html
git rm js/main.js
git rm js/plugins.js
git rm js/vendor/bootstrap.js
git rm js/vendor/bootstrap.min.js
git rm js/vendor/jquery-1.11.2.min.js
git rm js/vendor/modernizr-2.8.3-respond-1.4.2.min.js
git rm js/vendor/npm.js
git rm videos/video.mp4
